[package]
name = "jsonwebtokens-cognito"
version = "0.1.0-alpha.9"
authors = ["Robert Bragg <robert@sixbynine.org>"]
edition = "2018"
repository = "https://github.com/rib/jsonwebtokens-cognito"
documentation = "https://docs.rs/jsonwebtokens-cognito/"
readme = "README.md"
license = "MIT"
keywords = ["jwt", "jwk", "jwks", "token", "cognito"]
categories = ["authentication"]
description = "Decodes and verifies Json Web Tokens issued by AWS Cognito"

[dependencies]
jsonwebtokens = "1.0.0-alpha"
reqwest = { version = "~0.11.3", features=["json"] }
serde = { version="~1.0.126", features=["derive"] }
serde_json = "1"

[dev-dependencies]
async-std = { version = "~1.9.0", features = [ "attributes" ] }
